/**
 * This is not a production server yet!
 * This is only a minimal backend to get started.
 */

import { Logger } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';

import { AppModule } from './app/app.module';

async function bootstrap() {
  const testBasicToken =
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJadXJpY2ggQWRtaW4gVG9ja2VuIiwiaWF0IjoxNzI5Nzg5NTE3LCJleHAiOjE3NjEzMjczNTUsImF1ZCI6ImxvY2FsaG9zdCIsInN1YiI6ImFkbWluQGxvY2FsaG9zdCJ9.j9iVb_zFrqloKVZPA2uXAu8LC1lVT3sX6Plk9dampUk';
  const testAdminToken =
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJadXJpY2ggQWRtaW4gVG9ja2VuIiwiaWF0IjoxNzI5Nzg5NTE3LCJleHAiOjE3NjEzMjczNTUsImF1ZCI6ImxvY2FsaG9zdCIsInN1YiI6ImFkbWluQGxvY2FsaG9zdCIsInJvbGVzIjoiYWRtaW4ifQ.6nW693nectAb4FRkM-7XyXl7RD-5BITpInTqhmrrZhk';

  const app = await NestFactory.create(AppModule);
  const globalPrefix = 'api';
  app.setGlobalPrefix(globalPrefix);

  const config = new DocumentBuilder()
    .setTitle('Zurich Backend API')
    .setDescription(
      `Zurich Backend API
      <p>**UNSAFE For testing only</p> 
      <p>Normal Token ${testBasicToken}</p>
      <p>Admin Token ${testAdminToken}</p>
      <p>Generated By: http://jwtbuilder.jamiekurtz.com/</p>
      `
    )
    .setVersion('1.0')
    .addBearerAuth(
      { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
      'jwt'
    )
    .build();

  const documentFactory = () => SwaggerModule.createDocument(app, config);

  SwaggerModule.setup('api', app, documentFactory);

  const port = process.env.BACKEND_PORT || 3001;
  await app.listen(port);
  Logger.log(
    `🚀 Application is running on: http://localhost:${port}/${globalPrefix}`
  );
}

bootstrap();
